CUSTOM_MATRIX = lite
SRC += matrix.c
I2C_DRIVER_REQUIRED = yes

# Custom config
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes
NKRO_DEFAULT_ON = yes
